spring.application.name=SupportDesk

server.port=${SERVER_PORT:8080}

# spring.mongodb.uri=mongodb://app_user:pwd12345@localhost:27017/?authSource=support_desk_db
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=support_desk_db
spring.mongodb.authentication-database=support_desk_db
spring.mongodb.username=app_user
spring.mongodb.password=abcd12345

spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.indent-output=true

server.web.error.include-message=always
spring.web.errors.include-message=always
spring.web.errors.include-binding-errors=always
spring.web.errors.include-stacktrace=never

logging.level.root=INFO
logging.level.com.example.supportdesk=DEBUG