server.port = 8080

spring.output.ansi.enabled=ALWAYS

logging.level.com.example.assettracker=DEBUG

spring.jackson.serialization.indent_output=true

spring.web.errors.include-message=always
spring.we.errors.include-stacktrace=never

# Later for MongoDB
# spring.data.mongodb.uri=mongodb://localhost:27017/assettracker