#### Try to access tickets without token - should return 401 Unauthorized
GET http://localhost:8080/api/tickets

### Tasks
### 1. Register success -> expect 201 with a token
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Amir",
  "email": "amir@example.com",
  "password": "password123"
}
### eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpc3MiOiJhc3NldC10cmFja2VyIiwibmFtZSI6IkFtaXIiLCJleHAiOjE3ODUzODgzOTIsImlhdCI6MTc4NTM4NDc5MiwidXNlcklkIjoiNmE2YWNmNThkNTY2ZjJjZjJjMmRkOGJmIn0.M9Nx4Ty6HjxOCjEqbhK9sUTsXh-d24ztYCYJjEt3WbY
### 2. Login success -> expect 200 with a token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "amir@example.com",
  "password": "password123"
}

### 3. Duplicate email -> expect 409
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Amir Again",
  "email": "amir@example.com",
  "password": "password123"
}

### 4. Wrong password -> expect 401
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "amir@example.com",
  "password": "wrongpassword"
}

### 5. Get tickets with token -> expect 200
#### Try to access tickets without token - should return 401 Unauthorized
GET http://localhost:8080/api/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpc3MiOiJhc3NldC10cmFja2VyIiwibmFtZSI6IkFtaXIiLCJleHAiOjE3ODUzODkyODcsImlhdCI6MTc4NTM4NTY4NywidXNlcklkIjoiNmE2YWNmZjFkNTY2ZjJjZjJjMmRkOGMwIn0.EKOYsIjU9SP_9Z4gAiyaFcfygkFpKptUkDFECdOPyNc
