### Get all tickets
GET http://localhost:8080/api/tickets

### Get one ticket by ID 
GET http://localhost:8080/api/tickets/6a599e594004cddb459c5681

### Get a missing ticket
GET http://localhost:8080/api/tickets/000000000000000000000000