### Get all tickets
GET http://localhost:8080/api/tickets

### Get existing ticket
GET http://localhost:8080/api/tickets/T001

### Get missing ticket (Triggers 404)
GET http://localhost:8080/api/tickets/T999

### Create a Valid Ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "VPN connection not working",
  "description": "User cannot connect to company VPN from home.",
  "category": "Network",
  "priority": "MEDIUM",
  "createdBy": "siti@example.com"
}

### Create an Invalid Ticket (Triggers 400 Validation Error)
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "",
  "description": "",
  "category": "",
  "priority": "",
  "createdBy": ""
}
