spring.application.name=supportdesk

server.port=${SERVER_PORT:8080}

# spring.mongodb.uri=mongodb://app_user:pwd12345@localhost:27017/?authSource=asset_tracker_db
spring.mongodb.host=${MONGODB_HOST:localhost}
spring.mongodb.port=${MONGODB_PORT:27017}
spring.mongodb.database=${MONGODB_DATABASE:asset_tracker_db}
spring.mongodb.authentication-database=${MONGODB_AUTHENTICATION_DATABASE:asset_tracker_db}
spring.mongodb.username=${MONGODB_USERNAME}
spring.mongodb.password=${MONGODB_PASSWORD}

spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.indent-output=true

server.web.error.include-message=always
spring.web.errors.include-message=always
spring.web.errors.include-binding-errors=always
spring.web.errors.include-stacktrace=never

logging.level.root=INFO
logging.level.com.example.assettracker=DEBUG

# Day 9 Demo JWT Settings
app.jwt.secret=${JWT_SECRET:secret}
app.jwt.expiration=${JWT_EXPIRATION_MINUTES:60}
# export JWT_SECRET=secret
# export JWT_EXPIRATION_MINUTES=60